services:
    selenium-hub:
        image: selenium/hub:latest
        container_name: selenium-hub
        restart: always
        ports:
            - '4442:4442'
            - '4443:4443'
            - '4444:4444'

    chrome:
        image: selenium/node-chrome:latest
        shm_size: 2gb
        depends_on:
            - selenium-hub
        environment:
            - SE_EVENT_BUS_HOST=selenium-hub
            - SE_EVENT_BUS_PUBLISH_PORT=4442
            - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
            - SE_SESSION_REQUEST_TIMEOUT=5
            - SE_NODE_MAX_SESSIONS=4
            - VNC_NO_PASSWORD=1

    firefox:
        image: selenium/node-firefox:latest
        shm_size: 2gb
        depends_on:
            - selenium-hub
        environment:
            - SE_EVENT_BUS_HOST=selenium-hub
            - SE_EVENT_BUS_PUBLISH_PORT=4442
            - SE_EVENT_BUS_SUBSCRIBE_PORT=4443

    allure:
        image: frankescobar/allure-docker-service
        environment:
            CHECK_RESULTS_EVERY_SECONDS: 1
            KEEP_HISTORY: 1
        ports:
            - '5050:5050'
        volumes:
            - ./allure-results:/app/allure-results
            - ./allure-reports:/app/default-reports

    allure-ui:
        image: frankescobar/allure-docker-service-ui
        environment:
            ALLURE_DOCKER_PUBLIC_API_URL: 'http://localhost:5050'
            ALLURE_DOCKER_PUBLIC_API_URL_PREFIX: ''
        ports:
            - '5252:5252'

volumes:
    allure-results:
    allure-reports:
